# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo Linting code
      - flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
      - flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
  
  build:
    commands:
      - echo Running unit tests
      - nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
  
  post_build:
    commands:
      - echo Build completed
      - mkdir -p build
      - cp -r ./* build/
      - cd build
      - zip -r app.zip .

artifacts:
  files:
    - build/app.zip
  name: my-app-artifact
